try:
    num = int (input("Enter you number"))
    print(num)
except ValueError as ex:
    print(ex)

print("I am outside the try block")    


try:
    num1 = int(input("Enter a number:"))
    num2 = int(input("Enter a number:"))
    result = num1/num2
    print("Result is :",result)
    print("Result is :",result1)

except ZeroDivisionError:
    print("Division by zero is not possible")
except ValueError:
    print("Kindly enter numerical value ")    
except NameError:
    print("The exception varible is not defined")

finally:
 print("I will execute no matter what happens")


valid = False
while not valid:
    try:
       n = int(input("enter a number"))
       while n%2 == 0:
           print("bye") 
           valid = True
    except ValueError:
        print("Invalid")
